-- Per-student adaptive content.
-- content_adaptations caches one rendered variant per (learner, content, code)
-- so the AI / transform engine is not re-invoked for identical requests and
-- offline clients can reuse previously generated variants.
CREATE TABLE content_adaptations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id        BIGINT NOT NULL,
    content_id        BIGINT NOT NULL,
    adaptation_code   VARCHAR(32) NOT NULL,
    source_text_hash  VARCHAR(64) NOT NULL,
    adapted_text      TEXT NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_adapt_learner_content_code UNIQUE (learner_id, content_id, adaptation_code)
);

-- Attributable, auditable adaptation/feedback events.
CREATE TABLE adaptation_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id   BIGINT NOT NULL,
    content_id   BIGINT,
    event_type   VARCHAR(40) NOT NULL,
    detail       VARCHAR(2000),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_adapt_learner_content ON content_adaptations (learner_id, content_id);
CREATE INDEX idx_adapt_events_learner ON adaptation_events (learner_id, content_id);
