spring:
  datasource:
    url:      jdbc:postgresql://postgres:5432/accessibledocs
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

fastapi:
  base-url: ${FASTAPI_BASE_URL:http://accessible-docs:8000}